# import all the modules

In [1]:
#imports
#numpy, pandas, scipy, math, matplotlib

import numpy as np
import pandas as pd
import scipy
from math import sqrt
import matplotlib.pyplot as plt

# RMSE = Square Root of MSE ( mean squared error)
from math import sqrt

#estimator
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn import linear_model

#model metrtics
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

#cross validation
from sklearn.model_selection import train_test_split

# import the data

In [84]:
#data
rawData=pd.read_csv ("Credit_One_Data.csv")

In [85]:
rawData.head()

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  Unnamed: 0.1.1.1  ID  LIMIT_BAL  \
0           0             0               0                 0   1      20000   
1           1             1               1                 1   2     120000   
2           2             2               2                 2   3      90000   
3           3             3               3                 3   4      50000   
4           4             4               4                 4   5      50000   

   SEX  EDUCATION  MARRIAGE  AGE  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  \
0    0          3         1   24  ...          0          0          0   
1    0          3         2   26  ...       3272       3455       3261   
2    0          3         2   34  ...      14331      14948      15549   
3    0          3         1   37  ...      28314      28959      29547   
4    1          3         1   57  ...      20940      19146      19131   

   PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0         0       689         0         0         0         0   
1         0      1000      1000      1000         0      2000   
2      1518      1500      1000      1000      1000      5000   
3      2000      2019      1200      1100      1069      1000   
4      2000     36681     10000      9000       689       679   

   default payment next month  
0                           0  
1                           0  
2                           1  
3                           1  
4                           1  

[5 rows x 29 columns]

In [2]:
#data
rawData=pd.read_csv ("Credit_One_Data.csv")

In [3]:
rawData.head()

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  Unnamed: 0.1.1.1  ID  LIMIT_BAL  \
0           0             0               0                 0   1      20000   
1           1             1               1                 1   2     120000   
2           2             2               2                 2   3      90000   
3           3             3               3                 3   4      50000   
4           4             4               4                 4   5      50000   

   SEX  EDUCATION  MARRIAGE  AGE  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  \
0    0          3         1   24  ...          0          0          0   
1    0          3         2   26  ...       3272       3455       3261   
2    0          3         2   34  ...      14331      14948      15549   
3    0          3         1   37  ...      28314      28959      29547   
4    1          3         1   57  ...      20940      19146      19131   

   PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0         0       689         0         0         0         0   
1         0      1000      1000      1000         0      2000   
2      1518      1500      1000      1000      1000      5000   
3      2000      2019      1200      1100      1069      1000   
4      2000     36681     10000      9000       689       679   

   default payment next month  
0                           0  
1                           0  
2                           1  
3                           1  
4                           1  

[5 rows x 29 columns]

In [4]:
rawData.dtypes

Unnamed: 0                    int64
Unnamed: 0.1                  int64
Unnamed: 0.1.1                int64
Unnamed: 0.1.1.1              int64
ID                            int64
LIMIT_BAL                     int64
SEX                           int64
EDUCATION                     int64
MARRIAGE                      int64
AGE                           int64
PAY_0                         int64
PAY_2                         int64
PAY_3                         int64
PAY_4                         int64
PAY_5                         int64
PAY_6                         int64
BILL_AMT1                     int64
BILL_AMT2                     int64
BILL_AMT3                     int64
BILL_AMT4                     int64
BILL_AMT5                     int64
BILL_AMT6                     int64
PAY_AMT1                      int64
PAY_AMT2                      int64
PAY_AMT3                      int64
PAY_AMT4                      int64
PAY_AMT5                      int64
PAY_AMT6                    

# examine the structure of the data

In [5]:
rawData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  30000 non-null  int64
 1   Unnamed: 0.1                30000 non-null  int64
 2   Unnamed: 0.1.1              30000 non-null  int64
 3   Unnamed: 0.1.1.1            30000 non-null  int64
 4   ID                          30000 non-null  int64
 5   LIMIT_BAL                   30000 non-null  int64
 6   SEX                         30000 non-null  int64
 7   EDUCATION                   30000 non-null  int64
 8   MARRIAGE                    30000 non-null  int64
 9   AGE                         30000 non-null  int64
 10  PAY_0                       30000 non-null  int64
 11  PAY_2                       30000 non-null  int64
 12  PAY_3                       30000 non-null  int64
 13  PAY_4                       30000 non-null  int64
 14  PAY_5 

In [6]:
# drop columns

rawData.drop(columns=['Unnamed: 0', 'Unnamed: 0.1'])

Unnamed: 0.1.1  Unnamed: 0.1.1.1     ID  LIMIT_BAL  SEX  EDUCATION  \
0                   0                 0      1      20000    0          3   
1                   1                 1      2     120000    0          3   
2                   2                 2      3      90000    0          3   
3                   3                 3      4      50000    0          3   
4                   4                 4      5      50000    1          3   
...               ...               ...    ...        ...  ...        ...   
29995           29995             29995  29996     220000    1          1   
29996           29996             29996  29997     150000    1          1   
29997           29997             29997  29998      30000    1          3   
29998           29998             29998  29999      80000    1          1   
29999           29999             29999  30000      50000    1          3   

       MARRIAGE  AGE  PAY_0  PAY_2  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  \
0             1   24      2      2  ...          0          0          0   
1             2   26     -1      2  ...       3272       3455       3261   
2             2   34      0      0  ...      14331      14948      15549   
3             1   37      0      0  ...      28314      28959      29547   
4             1   57     -1      0  ...      20940      19146      19131   
...         ...  ...    ...    ...  ...        ...        ...        ...   
29995         1   39      0      0  ...      88004      31237      15980   
29996         2   43     -1     -1  ...       8979       5190          0   
29997         2   37      4      3  ...      20878      20582      19357   
29998         1   41      1     -1  ...      52774      11855      48944   
29999         1   46      0      0  ...      36535      32428      15313   

       PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0             0       689         0         0         0         0   
1             0      1000      1000      1000         0      2000   
2          1518      1500      1000      1000      1000      5000   
3          2000      2019      1200      1100      1069      1000   
4          2000     36681     10000      9000       689       679   
...         ...       ...       ...       ...       ...       ...   
29995      8500     20000      5003      3047      5000      1000   
29996      1837      3526      8998       129         0         0   
29997         0         0     22000      4200      2000      3100   
29998     85900      3409      1178      1926     52964      1804   
29999      2078      1800      1430      1000      1000      1000   

       default payment next month  
0                               0  
1                               0  
2                               1  
3                               1  
4                               1  
...                           ...  
29995                           1  
29996                           1  
29997                           0  
29998                           0  
29999                           0  

[30000 rows x 27 columns]

In [7]:
rawData.head()

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  Unnamed: 0.1.1.1  ID  LIMIT_BAL  \
0           0             0               0                 0   1      20000   
1           1             1               1                 1   2     120000   
2           2             2               2                 2   3      90000   
3           3             3               3                 3   4      50000   
4           4             4               4                 4   5      50000   

   SEX  EDUCATION  MARRIAGE  AGE  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  \
0    0          3         1   24  ...          0          0          0   
1    0          3         2   26  ...       3272       3455       3261   
2    0          3         2   34  ...      14331      14948      15549   
3    0          3         1   37  ...      28314      28959      29547   
4    1          3         1   57  ...      20940      19146      19131   

   PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0         0       689         0         0         0         0   
1         0      1000      1000      1000         0      2000   
2      1518      1500      1000      1000      1000      5000   
3      2000      2019      1200      1100      1069      1000   
4      2000     36681     10000      9000       689       679   

   default payment next month  
0                           0  
1                           0  
2                           1  
3                           1  
4                           1  

[5 rows x 29 columns]

#### not sure why data.drop(columns) function didn't work?

### set 'limit_bal', 'sex', 'educaion', 'marriage', 'age' = X,  'default payment next month'  =  y dependable

In [82]:
#selecting data
#features
X = rawData.iloc[:,4:7]
print('Summary of feature sample')
X.head()

Summary of feature sample


ID  LIMIT_BAL  SEX
0   1      20000    0
1   2     120000    0
2   3      90000    0
3   4      50000    0
4   5      50000    1

In [9]:
# select the Y variable
y = rawData['default payment next month']
y

0        0
1        0
2        1
3        1
4        1
        ..
29995    1
29996    1
29997    0
29998    0
29999    0
Name: default payment next month, Length: 30000, dtype: int64

In [10]:
#split data into traing / test set
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=.30, random_state=123)

In [11]:
# Modeling - Linear Regression

algo_lr = LinearRegression()
model_lr = algo_lr.fit(X_train, y_train)
print(cross_val_score(model_lr, X, y, cv=3))
model_lr.score(X_train,y_train)

[0.013709   0.02670667 0.02725347]


0.02424392934920694

In [12]:
# Make Predictions

preds = model_lr.predict(X_test)
predRsquared = r2_score(y_test,preds)
rmse = sqrt(mean_squared_error(y_test, preds))
print('R Squared: %.3f' % predRsquared)  # the higher the better ( overfitting)
print('RMSE: %.3f' % rmse)               # the lower the better

R Squared: 0.026
RMSE: 0.406


In [13]:
# Modeling - Random Forest Regressor

algo_rfr = RandomForestRegressor()
model_rfr = algo_rfr.fit(X_train, y_train)
print(cross_val_score(model_rfr, X, y, cv=3))
model_rfr.score(X_train,y_train)

[-0.1285971  -0.20710596 -0.35317396]


0.8337278916503605

In [14]:
# Make Predictions

preds = model_rfr.predict(X_test)
predRsquared = r2_score(y_test,preds)
rmse = sqrt(mean_squared_error(y_test, preds))
print('R Squared: %.3f' % predRsquared)  # the higher the better ( overfitting)
print('RMSE: %.3f' % rmse)               # the lower the better

R Squared: -0.199
RMSE: 0.451


In [15]:
# Modeling - SVR

algo_svr = SVR()
model_svr = algo_svr.fit(X_train, y_train)
print(cross_val_score(model_svr, X, y, cv=3))
model_svr.score(X_train,y_train)

[-0.09114694 -0.09502519 -0.07113973]


-0.0877846689213071

In [16]:
# Make Predictions

preds = model_svr.predict(X_test)
predRsquared = r2_score(y_test,preds)
rmse = sqrt(mean_squared_error(y_test, preds))
print('R Squared: %.3f' % predRsquared)  # the higher the better ( overfitting)
print('RMSE: %.3f' % rmse)               # the lower the better

R Squared: -0.080
RMSE: 0.428


In [17]:
# modeling format

algosClass = []
algosClass.append(('Random Forest Regressor',RandomForestRegressor()))
algosClass.append(('Linear Regression',LinearRegression()))
algosClass.append(('Support Vector Regression',SVR()))

In [18]:
# Rregression
results = []
names = []
for name, model in algosClass:
    result = cross_val_score(model, X, y, cv=3, scoring='r2')
    names.append(name)
    results.append(result)

In [19]:
# print result

for i in range(len(names)):
    print(names[i],results[i].mean())

Random Forest Regressor -0.19254552859036078
Linear Regression 0.02255637963950034
Support Vector Regression -0.08577061679367708


### include 'pay_amt 1-6' 'bill_amt1-6" to X dependent var, y='default payment'

In [20]:
#features
X = rawData.iloc[:,[3,4,5,6,7,14,15,16,17,18,19,20,21,22,23,24,25]]
print('Summary of feature sample')
X.head()

Summary of feature sample


Unnamed: 0.1.1.1  ID  LIMIT_BAL  SEX  EDUCATION  PAY_5  PAY_6  BILL_AMT1  \
0                 0   1      20000    0          3     -2     -2       3913   
1                 1   2     120000    0          3      0      2       2682   
2                 2   3      90000    0          3      0      0      29239   
3                 3   4      50000    0          3      0      0      46990   
4                 4   5      50000    1          3      0      0       8617   

   BILL_AMT2  BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0       3102        689          0          0          0         0       689   
1       1725       2682       3272       3455       3261         0      1000   
2      14027      13559      14331      14948      15549      1518      1500   
3      48233      49291      28314      28959      29547      2000      2019   
4       5670      35835      20940      19146      19131      2000     36681   

   PAY_AMT3  PAY_AMT4  
0         0         0  
1      1000      1000  
2      1000      1000  
3      1200      1100  
4     10000      9000

In [21]:
# select the Y variable
y = rawData['default payment next month']
print(y)

0        0
1        0
2        1
3        1
4        1
        ..
29995    1
29996    1
29997    0
29998    0
29999    0
Name: default payment next month, Length: 30000, dtype: int64


In [22]:
#split data into traing / test set
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=.30, random_state=123)
X_train.shape, X_test.shape

((21000, 17), (9000, 17))

In [23]:
# Modeling - Linear Regression

algo_lr = LinearRegression()
model_lr = algo_lr.fit(X_train, y_train)
print(cross_val_score(model_lr, X, y, cv=3))
model_lr.score(X_train,y_train)

[0.04585101 0.06690989 0.05365863]


0.06202229822588734

In [24]:
# Make Predictions

preds = model_lr.predict(X_test)
predRsquared = r2_score(y_test,preds)
rmse = sqrt(mean_squared_error(y_test, preds))
print('R Squared: %.3f' % predRsquared)  # the higher the better ( overfitting)
print('RMSE: %.3f' % rmse)               # the lower the better

R Squared: 0.052
RMSE: 0.401


In [25]:
# Modeling - Random Forest Regressor

algo_rfr = RandomForestRegressor()
model_rfr = algo_rfr.fit(X_train, y_train)
print(cross_val_score(model_rfr, X, y, cv=3))
model_rfr.score(X_train,y_train)

[-0.05346465  0.11162184  0.02098601]


0.8758078837456291

In [26]:
# Make Predictions

preds = model_rfr.predict(X_test)
predRsquared = r2_score(y_test,preds)
rmse = sqrt(mean_squared_error(y_test, preds))
print('R Squared: %.3f' % predRsquared)  # the higher the better ( overfitting)
print('RMSE: %.3f' % rmse)               # the lower the better

R Squared: 0.088
RMSE: 0.393


In [27]:
# Modeling - SVR

algo_svr = SVR()
model_svr = algo_svr.fit(X_train, y_train)
print(cross_val_score(model_svr, X, y, cv=3))
model_svr.score(X_train,y_train)

[-0.08995486 -0.09558515 -0.07035704]


-0.08202473904041052

In [28]:
# Make Predictions

preds = model_svr.predict(X_test)
predRsquared = r2_score(y_test,preds)
rmse = sqrt(mean_squared_error(y_test, preds))
print('R Squared: %.3f' % predRsquared)  # the higher the better ( overfitting)
print('RMSE: %.3f' % rmse)               # the lower the better

R Squared: -0.079
RMSE: 0.428


In [29]:
# modeling format

algosClass = []
algosClass.append(('Random Forest Regressor',RandomForestRegressor()))
algosClass.append(('Linear Regression',LinearRegression()))
algosClass.append(('Support Vector Regression',SVR()))

In [30]:
# Rregression
results = []
names = []
for name, model in algosClass:
    result = cross_val_score(model, X, y, cv=3, scoring='r2')
    names.append(name)
    results.append(result)

In [31]:
# print result

for i in range(len(names)):
    print(names[i],results[i].mean())

Random Forest Regressor 0.03178524393564371
Linear Regression 0.05547317762506269
Support Vector Regression -0.08529901756747349


### X = all columns except 'default payment', y = default payment

In [32]:
#features
X = rawData.iloc[:,3:26]
print('Summary of feature sample')
X.head()

Summary of feature sample


Unnamed: 0.1.1.1  ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  \
0                 0   1      20000    0          3         1   24      2   
1                 1   2     120000    0          3         2   26     -1   
2                 2   3      90000    0          3         2   34      0   
3                 3   4      50000    0          3         1   37      0   
4                 4   5      50000    1          3         1   57     -1   

   PAY_2  PAY_3  ...  BILL_AMT1  BILL_AMT2  BILL_AMT3  BILL_AMT4  BILL_AMT5  \
0      2     -1  ...       3913       3102        689          0          0   
1      2      0  ...       2682       1725       2682       3272       3455   
2      0      0  ...      29239      14027      13559      14331      14948   
3      0      0  ...      46990      48233      49291      28314      28959   
4      0     -1  ...       8617       5670      35835      20940      19146   

   BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  
0          0         0       689         0         0  
1       3261         0      1000      1000      1000  
2      15549      1518      1500      1000      1000  
3      29547      2000      2019      1200      1100  
4      19131      2000     36681     10000      9000  

[5 rows x 23 columns]

In [33]:
# select the Y variable
y = rawData['default payment next month']
y

0        0
1        0
2        1
3        1
4        1
        ..
29995    1
29996    1
29997    0
29998    0
29999    0
Name: default payment next month, Length: 30000, dtype: int64

In [34]:
#split data into traing / test set
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=.30, random_state=123)
X_train.shape, X_test.shape

((21000, 23), (9000, 23))

In [35]:
# Modeling - Linear Regression

algo_lr = LinearRegression()
model_lr = algo_lr.fit(X_train, y_train)
print(cross_val_score(model_lr, X, y, cv=3))
model_lr.score(X_train,y_train)

[0.10419513 0.13240865 0.12333112]


0.12467644100612119

In [36]:
# Make Predictions

preds = model_lr.predict(X_test)
predRsquared = r2_score(y_test,preds)
rmse = sqrt(mean_squared_error(y_test, preds))
print('R Squared: %.3f' % predRsquared)  # the higher the better ( overfitting)
print('RMSE: %.3f' % rmse)               # the lower the better

R Squared: 0.118
RMSE: 0.387


In [37]:
# Modeling - Random Forest Regressor

algo_rfr = RandomForestRegressor()
model_rfr = algo_rfr.fit(X_train, y_train)
print(cross_val_score(model_rfr, X, y, cv=3))
model_rfr.score(X_train,y_train)

[0.03834003 0.20757697 0.05163251]


0.8872897899555092

In [38]:
# Make Predictions

preds = model_rfr.predict(X_test)
predRsquared = r2_score(y_test,preds)
rmse = sqrt(mean_squared_error(y_test, preds))
print('R Squared: %.3f' % predRsquared)  # the higher the better ( overfitting)
print('RMSE: %.3f' % rmse)               # the lower the better

R Squared: 0.175
RMSE: 0.374


In [39]:
# Modeling - SVR

algo_svr = SVR()
model_svr = algo_svr.fit(X_train, y_train)
print(cross_val_score(model_svr, X, y, cv=3))
model_svr.score(X_train,y_train)

[-0.09024766 -0.09550029 -0.07039341]


-0.08238133246383406

In [40]:
# Make Predictions

preds = model_svr.predict(X_test)
predRsquared = r2_score(y_test,preds)
rmse = sqrt(mean_squared_error(y_test, preds))
print('R Squared: %.3f' % predRsquared)  # the higher the better ( overfitting)
print('RMSE: %.3f' % rmse)               # the lower the better

R Squared: -0.080
RMSE: 0.428


In [41]:
# print result

for i in range(len(names)):
    print(names[i],results[i].mean())

Random Forest Regressor 0.03178524393564371
Linear Regression 0.05547317762506269
Support Vector Regression -0.08529901756747349


###  X='limit_bal'  'bill_amt1-bill_amt6' 'pay_amt1-pay_amt6', y=  'default payment' 

In [42]:
#features
X = rawData.iloc[:,[3,14,15,16,17,18,19,20,21,22,23,24,25]]
print('Summary of feature sample')
X.head()

Summary of feature sample


Unnamed: 0.1.1.1  PAY_5  PAY_6  BILL_AMT1  BILL_AMT2  BILL_AMT3  BILL_AMT4  \
0                 0     -2     -2       3913       3102        689          0   
1                 1      0      2       2682       1725       2682       3272   
2                 2      0      0      29239      14027      13559      14331   
3                 3      0      0      46990      48233      49291      28314   
4                 4      0      0       8617       5670      35835      20940   

   BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  
0          0          0         0       689         0         0  
1       3455       3261         0      1000      1000      1000  
2      14948      15549      1518      1500      1000      1000  
3      28959      29547      2000      2019      1200      1100  
4      19146      19131      2000     36681     10000      9000

In [43]:
# select the Y variable
y = rawData['default payment next month']
y

0        0
1        0
2        1
3        1
4        1
        ..
29995    1
29996    1
29997    0
29998    0
29999    0
Name: default payment next month, Length: 30000, dtype: int64

In [44]:
#split data into traing / test set
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=.30, random_state=123)
X_train.shape, X_test.shape

((21000, 13), (9000, 13))

In [45]:
# Modeling - Linear Regression

algo_lr = LinearRegression()
model_lr = algo_lr.fit(X_train, y_train)
print(cross_val_score(model_lr, X, y, cv=3))
model_lr.score(X_train,y_train)

[0.04483207 0.06217589 0.04400276]


0.05701463170357335

In [46]:
# Make Predictions

preds = model_lr.predict(X_test)
predRsquared = r2_score(y_test,preds)
rmse = sqrt(mean_squared_error(y_test, preds))
print('R Squared: %.3f' % predRsquared)  # the higher the better ( overfitting)
print('RMSE: %.3f' % rmse)               # the lower the better

R Squared: 0.046
RMSE: 0.402


In [47]:
# Modeling - Random Forest Regressor

algo_rfr = RandomForestRegressor()
model_rfr = algo_rfr.fit(X_train, y_train)
print(cross_val_score(model_rfr, X, y, cv=3))
model_rfr.score(X_train,y_train)

[-0.15152972  0.089519   -0.03418114]


0.8726859489736821

In [48]:
# Make Predictions

preds = model_rfr.predict(X_test)
predRsquared = r2_score(y_test,preds)
rmse = sqrt(mean_squared_error(y_test, preds))
print('R Squared: %.3f' % predRsquared)  # the higher the better ( overfitting)
print('RMSE: %.3f' % rmse)               # the lower the better

R Squared: 0.058
RMSE: 0.400


In [49]:
# Modeling - SVR

algo_svr = SVR()
model_svr = algo_svr.fit(X_train, y_train)
print(cross_val_score(model_svr, X, y, cv=3))
model_svr.score(X_train,y_train)

[-0.08982572 -0.09488572 -0.07134719]


-0.07968018737483318

In [50]:
# Make Predictions

preds = model_svr.predict(X_test)
predRsquared = r2_score(y_test,preds)
rmse = sqrt(mean_squared_error(y_test, preds))
print('R Squared: %.3f' % predRsquared)  # the higher the better 
print('RMSE: %.3f' % rmse)               # the lower the better

R Squared: -0.079
RMSE: 0.428


In [51]:
# modeling format

algosClass = []
algosClass.append(('Random Forest Regressor',RandomForestRegressor()))
algosClass.append(('Linear Regression',LinearRegression()))
algosClass.append(('Support Vector Regression',SVR()))

In [52]:
# Rregression
results = []
names = []
for name, model in algosClass:
    result = cross_val_score(model, X, y, cv=3, scoring='r2')
    names.append(name)
    results.append(result)

In [53]:
# print result

for i in range(len(names)):
    print(names[i],results[i].mean())

Random Forest Regressor -0.03619739635112851
Linear Regression 0.05033690549656866
Support Vector Regression -0.0853528785713058


## X=edu, age, bill_amt1-6, pay_amt1-6, default payment, y=limit_bal

In [54]:
#features
X = rawData.iloc[:,[5,7,14,15,16,17,18,19,20,21,22,23,24,25,26]]
print('Summary of feature sample')
X.head()

Summary of feature sample


LIMIT_BAL  EDUCATION  PAY_5  PAY_6  BILL_AMT1  BILL_AMT2  BILL_AMT3  \
0      20000          3     -2     -2       3913       3102        689   
1     120000          3      0      2       2682       1725       2682   
2      90000          3      0      0      29239      14027      13559   
3      50000          3      0      0      46990      48233      49291   
4      50000          3      0      0       8617       5670      35835   

   BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  \
0          0          0          0         0       689         0         0   
1       3272       3455       3261         0      1000      1000      1000   
2      14331      14948      15549      1518      1500      1000      1000   
3      28314      28959      29547      2000      2019      1200      1100   
4      20940      19146      19131      2000     36681     10000      9000   

   PAY_AMT5  
0         0  
1         0  
2      1000  
3      1069  
4       689

In [55]:
# discretize'LIMIT_BAL'

pd.qcut(rawData['LIMIT_BAL'], q=6)

0         (9999.999, 50000.0]
1         (80000.0, 140000.0]
2         (80000.0, 140000.0]
3         (9999.999, 50000.0]
4         (9999.999, 50000.0]
                 ...         
29995    (200000.0, 300000.0]
29996    (140000.0, 200000.0]
29997     (9999.999, 50000.0]
29998      (50000.0, 80000.0]
29999     (9999.999, 50000.0]
Name: LIMIT_BAL, Length: 30000, dtype: category
Categories (6, interval[float64]): [(9999.999, 50000.0] < (50000.0, 80000.0] < (80000.0, 140000.0] < (140000.0, 200000.0] < (200000.0, 300000.0] < (300000.0, 1000000.0]]

In [56]:
limitbal_qcut = pd.qcut(rawData['LIMIT_BAL'], q=6, labels=False)
y = limitbal_qcut
y

0        0
1        2
2        2
3        0
4        0
        ..
29995    4
29996    3
29997    0
29998    1
29999    0
Name: LIMIT_BAL, Length: 30000, dtype: int64

In [57]:
#split data into traing / test set
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=.30, random_state=123)
X_train.shape, X_test.shape

((21000, 15), (9000, 15))

In [58]:
#split data into traing / test set
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=.30, random_state=123)

In [59]:
# Modeling - Linear Regression

algo_lr = LinearRegression()
model_lr = algo_lr.fit(X_train, y_train)
print(cross_val_score(model_lr, X, y, cv=3))
model_lr.score(X_train,y_train)

[0.8606772  0.86719159 0.85287702]


0.8625974741522527

In [60]:
# Make Predictions

preds = model_lr.predict(X_test)
predRsquared = r2_score(y_test,preds)
rmse = sqrt(mean_squared_error(y_test, preds))
print('R Squared: %.3f' % predRsquared)  # the higher the better ( overfitting)
print('RMSE: %.3f' % rmse)               # the lower the better

R Squared: 0.860
RMSE: 0.667


In [61]:
# Modeling - Random Forest Regressor

algo_rfr = RandomForestRegressor()
model_rfr = algo_rfr.fit(X_train, y_train)
print(cross_val_score(model_rfr, X, y, cv=3))
model_rfr.score(X_train,y_train)

[1. 1. 1.]


1.0

In [62]:
# Make Predictions

preds = model_rfr.predict(X_test)
predRsquared = r2_score(y_test,preds)
rmse = sqrt(mean_squared_error(y_test, preds))
print('R Squared: %.3f' % predRsquared)  # the higher the better ( overfitting)
print('RMSE: %.3f' % rmse)               # the lower the better

R Squared: 1.000
RMSE: 0.000


In [63]:
# Modeling - SVR

algo_svr = SVR()
model_svr = algo_svr.fit(X_train, y_train)
print(cross_val_score(model_svr, X, y, cv=3))
model_svr.score(X_train,y_train)

[0.97383665 0.973837   0.97253164]


0.9746515503270463

In [64]:
# Make Predictions

preds = model_svr.predict(X_test)
predRsquared = r2_score(y_test,preds)
rmse = sqrt(mean_squared_error(y_test, preds))
print('R Squared: %.3f' % predRsquared)  # the higher the better ( overfitting)
print('RMSE: %.3f' % rmse)               # the lower the better

R Squared: 0.973
RMSE: 0.293


### X=edu, marriage,sex, age, pay_amt1-6, default payment, y=limit_bal

In [65]:
#features
X = rawData.iloc[:,[4,5,6,7,20,21,22,23,24,25,26]]
print('Summary of feature sample')
X.head()

Summary of feature sample


ID  LIMIT_BAL  SEX  EDUCATION  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0   1      20000    0          3          0          0         0       689   
1   2     120000    0          3       3455       3261         0      1000   
2   3      90000    0          3      14948      15549      1518      1500   
3   4      50000    0          3      28959      29547      2000      2019   
4   5      50000    1          3      19146      19131      2000     36681   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  
0         0         0         0  
1      1000      1000         0  
2      1000      1000      1000  
3      1200      1100      1069  
4     10000      9000       689

In [66]:
y=limitbal_qcut
y

0        0
1        2
2        2
3        0
4        0
        ..
29995    4
29996    3
29997    0
29998    1
29999    0
Name: LIMIT_BAL, Length: 30000, dtype: int64

In [67]:
# Modeling - Linear Regression

algo_lr = LinearRegression()
model_lr = algo_lr.fit(X_train, y_train)
print(cross_val_score(model_lr, X, y, cv=3))
model_lr.score(X_train,y_train)

[0.8594098  0.86560494 0.85033572]


0.8625974741522527

In [68]:
# Make Predictions

preds = model_lr.predict(X_test)
predRsquared = r2_score(y_test,preds)
rmse = sqrt(mean_squared_error(y_test, preds))
print('R Squared: %.3f' % predRsquared)  # the higher the better ( overfitting)
print('RMSE: %.3f' % rmse)               # the lower the better

R Squared: 0.860
RMSE: 0.667


In [69]:
# Modeling - Random Forest Regressor

algo_rfr = RandomForestRegressor()
model_rfr = algo_rfr.fit(X_train, y_train)
print(cross_val_score(model_rfr, X, y, cv=3))
model_rfr.score(X_train,y_train)

[1. 1. 1.]


1.0

In [70]:
# Make Predictions

preds = model_rfr.predict(X_test)
predRsquared = r2_score(y_test,preds)
rmse = sqrt(mean_squared_error(y_test, preds))
print('R Squared: %.3f' % predRsquared)  # the higher the better ( overfitting)
print('RMSE: %.3f' % rmse)               # the lower the better

R Squared: 1.000
RMSE: 0.000


In [71]:
# Modeling - SVR

algo_svr = SVR()
model_svr = algo_svr.fit(X_train, y_train)
print(cross_val_score(model_svr, X, y, cv=3))
model_svr.score(X_train,y_train)

[0.97468571 0.97434518 0.97312161]


0.9746515503270463

In [72]:
# Make Predictions

preds = model_svr.predict(X_test)
predRsquared = r2_score(y_test,preds)
rmse = sqrt(mean_squared_error(y_test, preds))
print('R Squared: %.3f' % predRsquared)  # the higher the better ( overfitting)
print('RMSE: %.3f' % rmse)               # the lower the better

R Squared: 0.973
RMSE: 0.293


## X=all columns, 'LIMIT_BAL' = y dependable

In [73]:
#selecting data
#features
X = rawData.iloc[:,4:27]
print('Summary of feature sample')
X.head()

Summary of feature sample


ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1      20000    0          3         1   24      2      2     -1     -1   
1   2     120000    0          3         2   26     -1      2      0      0   
2   3      90000    0          3         2   34      0      0      0      0   
3   4      50000    0          3         1   37      0      0      0      0   
4   5      50000    1          3         1   57     -1      0     -1      0   

   ...  BILL_AMT2  BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  \
0  ...       3102        689          0          0          0         0   
1  ...       1725       2682       3272       3455       3261         0   
2  ...      14027      13559      14331      14948      15549      1518   
3  ...      48233      49291      28314      28959      29547      2000   
4  ...       5670      35835      20940      19146      19131      2000   

   PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  
0       689         0         0         0  
1      1000      1000      1000         0  
2      1500      1000      1000      1000  
3      2019      1200      1100      1069  
4     36681     10000      9000       689  

[5 rows x 23 columns]

In [74]:
y=limitbal_qcut
y

0        0
1        2
2        2
3        0
4        0
        ..
29995    4
29996    3
29997    0
29998    1
29999    0
Name: LIMIT_BAL, Length: 30000, dtype: int64

In [75]:
#split data into traing / test set
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=.30, random_state=123)
X_train.shape, X_test.shape

((21000, 23), (9000, 23))

In [76]:
# Modeling - Linear Regression

algo_lr = LinearRegression()
model_lr = algo_lr.fit(X_train, y_train)
print(cross_val_score(model_lr, X, y, cv=3))
model_lr.score(X_train,y_train)

[0.86308051 0.86959874 0.85546076]


0.8653286548450352

In [77]:
# Make Predictions

preds = model_lr.predict(X_test)
predRsquared = r2_score(y_test,preds)
rmse = sqrt(mean_squared_error(y_test, preds))
print('R Squared: %.3f' % predRsquared)  # the higher the better 
print('RMSE: %.3f' % rmse)               # the lower the better

R Squared: 0.863
RMSE: 0.660


In [78]:
# Modeling - Random Forest Regressor

algo_rfr = RandomForestRegressor()
model_rfr = algo_rfr.fit(X_train, y_train)
print(cross_val_score(model_rfr, X, y, cv=3))
model_rfr.score(X_train,y_train)

[1. 1. 1.]


1.0

In [79]:
# Make Predictions

preds = model_rfr.predict(X_test)
predRsquared = r2_score(y_test,preds)
rmse = sqrt(mean_squared_error(y_test, preds))
print('R Squared: %.3f' % predRsquared)  # the higher the better ( overfitting)
print('RMSE: %.3f' % rmse)               # the lower the better

R Squared: 1.000
RMSE: 0.000


In [80]:
# Modeling - SVR

algo_svr = SVR()
model_svr = algo_svr.fit(X_train, y_train)
print(cross_val_score(model_svr, X, y, cv=3))
model_svr.score(X_train,y_train)

[0.9736394  0.97363954 0.97246916]


0.9744256067611811

In [81]:
# Make Predictions

preds = model_svr.predict(X_test)
predRsquared = r2_score(y_test,preds)
rmse = sqrt(mean_squared_error(y_test, preds))
print('R Squared: %.3f' % predRsquared)  # the higher the better ( overfitting)
print('RMSE: %.3f' % rmse)               # the lower the better

R Squared: 0.973
RMSE: 0.294
